#include <iostream>
#include<vector>
#include<string>
#include<algorithm>
#include<iterator>
#include<map>
#include<set>
#include<string>
#include<cstring>
#include<cstdio>
#include<stack>
#include<queue>
#include<math.h>
#include <utility>
#include <sstream> 
#include<bitset>
/* run this program using the console pauser or add your own getch, system("pause") or input loop */
using namespace std;

typedef long long ll;
typedef std::vector<ll> vi;

#define PI acos(-1)
#define E 2.718281828459

std::bitset<10000020> bs; // 10^7 + small extra bits should be enough for most prime-related problems
std::vector<ll> primes; // compact list of primes in form of vector<int>
void sieve(ll upperbound) { // create list of primes in [0 .. upperbound]
          int sieve_size = upperbound + 1; // add 1 to include upperbound
           bs.reset(); bs.flip(); // set all numbers to 1
            bs.set(0, false); bs.set(1, false); // except index 0 and 1
          for (ll i = 2; i <= sieve_size; i++) if (bs.test((size_t)i)) {
// cross out multiples of i starting from i * i! 
          for (ll j = i * i; j <= sieve_size; j += i) bs.set((size_t)j, false);
           primes.push_back((int)i);
    }
} 
vi primeFactors(ll N) {
      vi factors;          // vi "primes" (generated by sieve) is optional
      ll PF_idx = 0, PF = primes[PF_idx]; // using PF = 2, 3, 4, ..., is also ok.
      while ((PF * PF <= N)) { // stop at sqrt(N), but N can get smaller
        while (N % PF == 0) { 
		N /= PF; factors.push_back(PF); } // remove this PF
            PF = primes[++PF_idx]; // only consider primes!
            }
          if (N != 1) factors.push_back(N); // special case if N is actually a prime
      return factors;
}
int gcd(int a, int b)
{ 
       return (b == 0 ? a : gcd(b, a % b)); 
}

map<string,char> mp;
map<string,char>::iterator it;

void Sieve()
{
	for(int i=32;i<=127;i++)
	{
		string str;
		char c=i;
		for(int j=0;j<=7;j++)
		{
			int a=i;
			a=(a/pow(2,j));
    	    a=a%2;
    	    if(a==0) str = str + '/' ;
    	    else str=str+'\\' ;
		}
		mp[str]=c;
	}
	return;
}
int main(int argc, char** argv) {
	//freopen("c.txt","w",stdout);
	Sieve();
	int t;
	cin>>t;
	while(t--)
	{
		cin.ignore();
		char a[10][100];
		string ans;
		for(int i=0;i<10;i++)
		{
			cin>>a[i];
		}
		for(int j=1;j<strlen(a[0])-1;j++)
		{
			string c;
			for(int i=1;i<9;i++)
			{
				c=c+a[i][j];
			}
			it=mp.find(c);
			//cout<<c<<endl;
			ans=ans+it->second;
		}
		//cout<<"out"<<endl;
		cout<<ans<<endl;
	}
	return 0;	
}
