#include <iostream>
#include<vector>
#include<string>
#include<algorithm>
#include<iterator>
#include<map>
#include<set>
#include<string>
#include<cstring>
#include<cstdio>
#include<stack>
#include<queue>
#include<math.h>
#include <utility>
#include <sstream> 
#include<bitset>
/* run this program using the console pauser or add your own getch, system("pause") or input loop */
using namespace std;

typedef long long ll;
typedef vector<ll> vi;

#define PI acos(-1)
#define e 2.718281828459

bitset<10000010> bs; // 10^7 + small extra bits should be enough for most prime-related problems
vector<ll> primes; // compact list of primes in form of vector<int>
void sieve(ll upperbound) { // create list of primes in [0 .. upperbound]
          int sieve_size = upperbound + 1; // add 1 to include upperbound
           bs.reset(); bs.flip(); // set all numbers to 1
            bs.set(0, false); bs.set(1, false); // except index 0 and 1
          for (ll i = 2; i <= sieve_size; i++) if (bs.test((size_t)i)) {
// cross out multiples of i starting from i * i! 
          for (ll j = i * i; j <= sieve_size; j += i) bs.set((size_t)j, false);
           primes.push_back((int)i);
    }
} 
vi primeFactors(ll N) {
      vi factors;          // vi "primes" (generated by sieve) is optional
      ll PF_idx = 0, PF = primes[PF_idx]; // using PF = 2, 3, 4, ..., is also ok.
      while (N != 1 && (PF * PF <= N)) { // stop at sqrt(N), but N can get smaller
        while (N % PF == 0) { N /= PF; factors.push_back(PF); } // remove this PF
            PF = primes[++PF_idx]; // only consider primes!
            }
          if (N != 1) factors.push_back(N); // special case if N is actually a prime
      return factors;
}

int gcd(int a, int b)
{ 
       return (b == 0 ? a : gcd(b, a % b)); 
}
int main(int argc, char** argv) {
	//freopen("c.txt","w",stdout);
	sieve(10000000);
	ll n;
	while(cin>>n&&n)
	{
		n=abs(n);
		if(n==1){
			cout<<-1<<endl;
			continue;
		}
		vi result=primeFactors(n);
		//vi::iterator last = unique(result.begin(), result.end());
		set<ll> s;
		set<ll>::iterator it;
		for(int i=0;i<result.size();i++)
		s.insert(result[i]);
		it=s.end();
		if(s.size()==1||s.empty())cout<<-1<<endl;
		else {
			it--;
			cout<<*it<<endl;
		}
		//if(result.size()==1||result.empty())cout<<-1<<endl;
		//else cout<<result[result.size()-1]<<endl;
	}
	return 0;
}
