#include <iostream>
#include<vector>
#include<string>
#include<algorithm>
#include<iterator>
#include<map>
#include<set>
#include<string>
#include<cstring>
#include<cstdio>
#include<stack>
#include<queue>
#include<math.h>
#include <utility>
#include <sstream> 
#include<bitset>
/* run this program using the console pauser or add your own getch, system("pause") or input loop */
using namespace std;

typedef long long ll;
typedef std::vector<ll> vi;

#define PI acos(-1)
#define E 2.718281828459
#define speed      ios::sync_with_stdio(false);cin.tie(NULL); cout.tie(NULL);

std::bitset<10000020> bs; // 10^7 + small extra bits should be enough for most prime-related problems
std::vector<ll> primes; // compact list of primes in form of vector<int>
void sieve(ll upperbound) { // create list of primes in [0 .. upperbound]
          int sieve_size = upperbound + 1; // add 1 to include upperbound
           bs.reset(); bs.flip(); // set all numbers to 1
            bs.set(0, false); bs.set(1, false); // except index 0 and 1
          for (ll i = 2; i <= sieve_size; i++) if (bs.test((size_t)i)) {
// cross out multiples of i starting from i * i! 
          for (ll j = i * i; j <= sieve_size; j += i) bs.set((size_t)j, false);
           primes.push_back((int)i);
    }
} 
vi primeFactors(ll N) {
      vi factors;          // vi "primes" (generated by sieve) is optional
      ll PF_idx = 0, PF = primes[PF_idx]; // using PF = 2, 3, 4, ..., is also ok.
      while ((PF * PF <= N)) { // stop at sqrt(N), but N can get smaller
        while (N % PF == 0) { 
		N /= PF; factors.push_back(PF); } // remove this PF
            PF = primes[++PF_idx]; // only consider primes!
            }
          if (N != 1) factors.push_back(N); // special case if N is actually a prime
      return factors;
}
int gcd(int a, int b)
{ 
       return (b == 0 ? a : gcd(b, a % b)); 
}

int main(int argc, char** argv) {
	//freopen("c.txt","w",stdout);
	int t;
	scanf("%d",&t);
	bool c=false;
	while(t--)
	{
		if(c)cout<<endl;
		c=true;
		multimap<string,pair<ll,ll> > base;
		multimap<string,pair<ll,ll> >::iterator it;
		int d,h,l;
		cin>>d;
		string str;
		while(d--)
		{
			std::cin>>str>>l>>h;
			base.insert(make_pair(str,make_pair(l,h)));
		}
		/*it=base.begin();
		while(it!=base.end())
		{
			cout<<it->first<<" "<<it->second.first<<" "<<it->second.second<<endl;
			it++;
		}*/
		ll query,price;
		std::cin>>query;
		while(query--)
		{
			std::cin>>price;
			int count=0;
			string answer;
			it=base.begin();
			while(it!=base.end())
			{
				int LOW=it->second.first;
				int HIGH=it->second.second;
				//cout<<it->first<<" "<<LOW<<" "<<HIGH<<" "<<"price "<<price<<endl;
				if(price>=LOW&&price<=HIGH)
				{
					count++;
					if(count==1)
					{
						answer=it->first;
					}
					else
					{
						break;
					}
				}
				it++;
			}
			if(count==1)
			{
				cout<<answer<<endl;
			}
			else
			{
				cout<<"UNDETERMINED\n";
			}
		}
	}
	return 0;
}
