#include <iostream>
#include<vector>
#include<string>
#include<algorithm>
#include<iterator>
#include<map>
#include<set>
#include<string>
#include<cstring>
#include<cstdio>
#include<stack>
#include<queue>
#include<math.h>
#include <utility>
#include <sstream> 
#include<bitset>
/* run this program using the console pauser or add your own getch, system("pause") or input loop */
using namespace std;

typedef long long ll;
typedef std::vector<ll> vi;

#define PI acos(-1)
#define E 2.718281828459

std::bitset<10000020> bs; // 10^7 + small extra bits should be enough for most prime-related problems
std::vector<ll> primes; // compact list of primes in form of vector<int>
void sieve(ll upperbound) { // create list of primes in [0 .. upperbound]
          int sieve_size = upperbound + 1; // add 1 to include upperbound
           bs.reset(); bs.flip(); // set all numbers to 1
            bs.set(0, false); bs.set(1, false); // except index 0 and 1
          for (ll i = 2; i <= sieve_size; i++) if (bs.test((size_t)i)) {
// cross out multiples of i starting from i * i! 
          for (ll j = i * i; j <= sieve_size; j += i) bs.set((size_t)j, false);
           primes.push_back((int)i);
    }
} 
vi primeFactors(ll N) {
      vi factors;          // vi "primes" (generated by sieve) is optional
      ll PF_idx = 0, PF = primes[PF_idx]; // using PF = 2, 3, 4, ..., is also ok.
      while ((PF * PF <= N)) { // stop at sqrt(N), but N can get smaller
        while (N % PF == 0) { 
		N /= PF; factors.push_back(PF); } // remove this PF
            PF = primes[++PF_idx]; // only consider primes!
            }
          if (N != 1) factors.push_back(N); // special case if N is actually a prime
      return factors;
}
int gcd(int a, int b)
{ 
       return (b == 0 ? a : gcd(b, a % b)); 
}
/*bool is_prime(ll n)
{
	if(n==0||n==1)return false;
	if(n==2)return true;
	if(n%2==0)return false;
	for(int i=3;i<=sqrt(n);i+=2)
	{
		if(n%i==0)return false;
	}
	return true;
}*/
int main(int argc, char** argv) {
	//freopen("c.txt","w",stdout);
	string a,b;
	while(cin>>a>>b)
	{
		map<char,int> A;
		map<char,int> B;
		map<char,int>::iterator it;
		for(int i=0;i<a.length();i++)
		{
			A[a[i]]++;
		}
		for(int i=0;i<b.length();i++)
		{
			B[b[i]]++;
		}
		vector<int> x,y;
		it=A.begin();
		while(it!=A.end())
		{
			x.push_back(it->second);
			it++;
		}
		it=B.begin();
		while(it!=B.end())
		{
			y.push_back(it->second);
			it++;
		}
		sort(x.begin(),x.end());
		sort(y.begin(),y.end());
		bool f=false;
		for(int i=0;i<x.size();i++)
		{
			if(x[i]!=y[i])
			{
				f=true;
				break;
			}
		}
		if(f)cout<<"NO\n";
		else cout<<"YES\n";
	}
}
