#include <iostream>
#include<vector>
#include<string>
#include<algorithm>
#include<iterator>
#include<map>
#include<set>
#include<string>
#include<cstring>
#include<cstdio>
#include<stack>
#include<queue>
#include<math.h>
#include <utility>
#include <sstream> 
#include<bitset>
/* run this program using the console pauser or add your own getch, system("pause") or input loop */
using namespace std;

typedef long long ll;
typedef std::vector<ll> vi;

#define PI acos(-1)
#define E 2.718281828459

std::bitset<2250> bs; // 10^7 + small extra bits should be enough for most prime-related problems
std::vector<ll> primes; // compact list of primes in form of vector<int>
void sieve(ll upperbound) { // create list of primes in [0 .. upperbound]
          int sieve_size = upperbound + 1; // add 1 to include upperbound
           bs.reset(); bs.flip(); // set all numbers to 1
            bs.set(0, false); bs.set(1, false); // except index 0 and 1
          for (ll i = 2; i <= sieve_size; i++) if (bs.test((size_t)i)) {
// cross out multiples of i starting from i * i! 
          for (ll j = i * i; j <= sieve_size; j += i) bs.set((size_t)j, false);
           primes.push_back((int)i);
    }
} 
vi primeFactors(ll N) {
      vi factors;          // vi "primes" (generated by sieve) is optional
      ll PF_idx = 0, PF = primes[PF_idx]; // using PF = 2, 3, 4, ..., is also ok.
      while ((PF * PF <= N)) { // stop at sqrt(N), but N can get smaller
        while (N % PF == 0) { 
		N /= PF; factors.push_back(PF); } // remove this PF
            PF = primes[++PF_idx]; // only consider primes!
            }
          if (N != 1) factors.push_back(N); // special case if N is actually a prime
      return factors;
}
int gcd(int a, int b)
{ 
       return (b == 0 ? a : gcd(b, a % b)); 
}
map<char,int> m;
void sieve()
{
	m['A']='2';m['B']='2';m['C']='2';m['D']='3';m['E']='3';m['F']='3';
	m['G']='4';m['H']='4';m['I']='4';m['J']='5';m['K']='5';m['L']='5';
	m['M']='6';m['N']='6';m['O']='6';m['P']='7';m['R']='7';m['S']='7';
	m['T']='8';m['U']='8';m['V']='8';m['W']='9';m['X']='9';m['Y']='9';
}
int main(int argc, char** argv) {
	//freopen("c.txt","w",stdout);
	sieve();
	int t;
	cin>>t;
	while(t--)
	{
		int n;
		cin>>n;
		cin.ignore();
		string str;
		map<string,int> mp;map<string,int>::iterator it;
		while(n--)
		{
			cin>>str;
			string temp;
			for(int i=0;i<str.length();i++)
			{
				if(str[i]=='-')continue;
				if(str[i]>=65&&str[i]<=90)
				str[i]=m[str[i]];
				temp=temp+str[i];
				if(temp.length()==3)temp=temp+"-";
			}
			mp[temp]++;
		}
		it=mp.begin();
		int count=0;
		while(it!=mp.end())
		{
			if(it->second>1){
				cout<<it->first<<" "<<it->second<<endl;count++;
			}
			it++;
		}
		if(count==0)cout<<"No duplicates.\n";
		if(t)cout<<endl;
	}
   return 0;
}
